import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Wanderlust Next App",
  description: "Generated by wanderlust next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}